//! Page texts from `content/oldalak/*.md`, compiled into the binary and parsed once.
//!
//! Format: a frontmatter block of `key: "json string"` lines, then Markdown. `## Heading` starts a
//! section. `![alt](kep:<key>)` refers to an image generated by tools/images.py; a paragraph made
//! only of such images is a gallery.

use std::{collections::HashMap, sync::OnceLock};

use pulldown_cmark::{html, Event, HeadingLevel, Parser, Tag, TagEnd};

const FILES: &[(&str, &str)] = &[
    ("kezdolap", include_str!("../content/oldalak/kezdolap.md")),
    ("rolunk", include_str!("../content/oldalak/rolunk.md")),
    ("elerhetoseg", include_str!("../content/oldalak/elerhetoseg.md")),
    ("programjaink", include_str!("../content/oldalak/programjaink.md")),
    ("eloadoink", include_str!("../content/oldalak/eloadoink.md")),
    ("projektek", include_str!("../content/oldalak/projektek.md")),
    ("projektek-asztrofotok", include_str!("../content/oldalak/projektek-asztrofotok.md")),
    ("projektek-isstv", include_str!("../content/oldalak/projektek-isstv.md")),
    ("projektek-idojaras-muhold", include_str!("../content/oldalak/projektek-idojaras-muhold.md")),
];

/// The project subpages, in the order they are presented.
pub const PROJECTS: &[&str] =
    &["projektek-asztrofotok", "projektek-isstv", "projektek-idojaras-muhold"];

pub struct Doc {
    pub title: String,
    pub route: String,
    pub description: String,
    /// First sentence of the page, used on overview pages.
    pub excerpt: String,
    /// Blocks before the first `##` heading.
    pub intro: Vec<Block>,
    pub sections: Vec<Section>,
}

pub struct Section {
    pub heading: String,
    pub blocks: Vec<Block>,
}

pub enum Block {
    /// A rendered block (paragraph, list, ...).
    Html(String),
    /// One or more images standing alone in a paragraph.
    Images(Vec<ImageRef>),
}

#[derive(Clone)]
pub struct ImageRef {
    pub key: String,
    pub alt: String,
}

/// The parsed page `name` (file stem). Panics on an unknown name: that is a programming error.
pub fn doc(name: &str) -> &'static Doc {
    static DOCS: OnceLock<HashMap<&'static str, Doc>> = OnceLock::new();
    DOCS.get_or_init(|| FILES.iter().map(|&(name, src)| (name, parse(src))).collect())
        .get(name)
        .unwrap_or_else(|| panic!("unknown content page: {name}"))
}

impl Doc {
    pub fn section(&self, heading: &str) -> Option<&Section> {
        self.sections.iter().find(|s| s.heading == heading)
    }

    /// Every block of the page, intro first.
    pub fn blocks(&self) -> impl Iterator<Item = &Block> {
        self.intro.iter().chain(self.sections.iter().flat_map(|s| s.blocks.iter()))
    }

    pub fn images(&self) -> impl Iterator<Item = &ImageRef> {
        self.blocks().filter_map(|b| match b {
            Block::Images(images) => Some(images.iter()),
            Block::Html(_) => None,
        })
        .flatten()
    }
}

impl Section {
    pub fn html(&self) -> impl Iterator<Item = &str> {
        self.blocks.iter().filter_map(|b| match b {
            Block::Html(html) => Some(html.as_str()),
            Block::Images(_) => None,
        })
    }
}

fn parse(src: &'static str) -> Doc {
    let (front, body) = split_frontmatter(src);
    let field = |key: &str| front.get(key).cloned().unwrap_or_default();

    let mut intro = Vec::new();
    let mut sections: Vec<Section> = Vec::new();
    let mut block: Vec<Event> = Vec::new();
    let mut depth = 0usize;
    let mut heading: Option<String> = None;

    for event in Parser::new(body) {
        match &event {
            Event::Start(Tag::Heading { level: HeadingLevel::H2, .. }) if depth == 0 => {
                heading = Some(String::new());
                continue;
            }
            Event::End(TagEnd::Heading(HeadingLevel::H2)) if heading.is_some() => {
                let heading = heading.take().unwrap_or_default();
                sections.push(Section { heading: heading.trim().to_owned(), blocks: Vec::new() });
                continue;
            }
            Event::Text(text) | Event::Code(text) if heading.is_some() => {
                if let Some(heading) = heading.as_mut() {
                    heading.push_str(text);
                }
                continue;
            }
            _ if heading.is_some() => continue,
            Event::Start(_) => depth += 1,
            Event::End(_) => depth -= 1,
            _ => {}
        }
        block.push(event);
        if depth == 0 {
            let target = match sections.last_mut() {
                Some(section) => &mut section.blocks,
                None => &mut intro,
            };
            target.push(to_block(std::mem::take(&mut block)));
        }
    }

    let excerpt = match field("kivonat") {
        e if e.is_empty() => field("leiras"),
        e => e,
    };
    Doc {
        title: field("cim"),
        route: field("utvonal"),
        description: field("leiras"),
        excerpt,
        intro,
        sections,
    }
}

/// `key: "value"` lines between the leading `---` fences; values are JSON strings.
fn split_frontmatter(src: &'static str) -> (HashMap<String, String>, &'static str) {
    let mut fields = HashMap::new();
    let Some(rest) = src.trim_start_matches('\u{feff}').strip_prefix("---") else {
        return (fields, src);
    };
    let Some(end) = rest.find("\n---") else { return (fields, src) };
    for line in rest[..end].lines() {
        if let Some((key, value)) = line.split_once(':') {
            let value = value.trim();
            let value = serde_json::from_str::<String>(value).unwrap_or_else(|_| value.to_owned());
            fields.insert(key.trim().to_owned(), value);
        }
    }
    let body = &rest[end + 4..];
    (fields, body.strip_prefix('\n').or_else(|| body.strip_prefix("\r\n")).unwrap_or(body))
}

/// A paragraph that holds nothing but `kep:` images becomes a gallery; anything else is HTML.
fn to_block(events: Vec<Event>) -> Block {
    if let Some(images) = only_images(&events) {
        return Block::Images(images);
    }
    let mut out = String::new();
    html::push_html(&mut out, events.into_iter());
    Block::Html(out)
}

fn only_images(events: &[Event]) -> Option<Vec<ImageRef>> {
    let inner = events
        .strip_prefix(&[Event::Start(Tag::Paragraph)])?
        .strip_suffix(&[Event::End(TagEnd::Paragraph)])?;
    let mut images = Vec::new();
    let mut current: Option<ImageRef> = None;
    for event in inner {
        match event {
            Event::Start(Tag::Image { dest_url, .. }) => {
                let key = dest_url.strip_prefix("kep:")?;
                current = Some(ImageRef { key: key.to_owned(), alt: String::new() });
            }
            Event::Text(text) if current.is_some() => current.as_mut()?.alt.push_str(text),
            Event::End(TagEnd::Image) => images.push(current.take()?),
            Event::SoftBreak | Event::HardBreak => {}
            Event::Text(text) if text.trim().is_empty() => {}
            _ => return None,
        }
    }
    (!images.is_empty()).then_some(images)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_frontmatter_sections_and_galleries() {
        let doc = parse(
            "---\ncim: \"Próba\"\nutvonal: \"/proba\"\nkivonat: \"Első mondat.\"\n---\n\nBevezető [link](/x).\n\n## Képek\n\n![Hold](kep:asztro/hold)\n![Orion-köd](kep:asztro/orion-kod)\n\nSzöveg **vastag**.\n",
        );
        assert_eq!(doc.title, "Próba");
        assert_eq!(doc.route, "/proba");
        assert_eq!(doc.excerpt, "Első mondat.");
        assert!(matches!(&doc.intro[..], [Block::Html(h)] if h.contains("<a href=\"/x\">link</a>")));
        let section = doc.section("Képek").unwrap();
        match &section.blocks[0] {
            Block::Images(images) => {
                assert_eq!(images.len(), 2);
                assert_eq!(images[1].key, "asztro/orion-kod");
                assert_eq!(images[1].alt, "Orion-köd");
            }
            Block::Html(_) => panic!("expected a gallery"),
        }
        assert!(matches!(&section.blocks[1], Block::Html(h) if h.contains("<strong>vastag</strong>")));
    }

    #[test]
    fn every_page_parses_and_every_image_exists() {
        for &(name, _) in FILES {
            let doc = doc(name);
            assert!(!doc.title.is_empty(), "{name}: missing cim");
            assert!(doc.route.starts_with('/'), "{name}: bad utvonal");
            for image in doc.images() {
                assert!(crate::images::get(&image.key).is_some(), "{name}: unknown image {}", image.key);
                assert!(!image.alt.trim().is_empty(), "{name}: empty alt for {}", image.key);
            }
            for block in doc.blocks() {
                if let Block::Html(html) = block {
                    assert!(
                        !html.contains("\"kep:"),
                        "{name}: kep: image outside a standalone image paragraph \
                         (put it on its own line, plain-text alt, blank line before and after)"
                    );
                }
            }
        }
    }
}
