//! Generated by tools/images.py. Do not edit by hand.

pub struct Image {
    pub key: &'static str,
    pub width: u32,
    pub height: u32,
    pub widths: &'static [u32],
}

pub const IMAGES: &[Image] = &[
    Image {
        key: "asztro/hold",
        width: 1920,
        height: 2160,
        widths: &[640, 1280, 1920],
    },
    Image {
        key: "asztro/laguna-kod",
        width: 889,
        height: 546,
        widths: &[640, 889],
    },
    Image {
        key: "asztro/orion-kod",
        width: 1280,
        height: 2024,
        widths: &[640, 1280],
    },
    Image {
        key: "eloadok/bacsardi-laszlo",
        width: 945,
        height: 630,
        widths: &[480, 945],
    },
    Image {
        key: "eloadok/detre-ors-hunor",
        width: 945,
        height: 629,
        widths: &[480, 945],
    },
    Image {
        key: "eloadok/gschwindt-andras",
        width: 944,
        height: 629,
        widths: &[480, 944],
    },
    Image {
        key: "eloadok/horvath-gyula",
        width: 945,
        height: 630,
        widths: &[480, 945],
    },
    Image {
        key: "eloadok/kovacs-kalman",
        width: 945,
        height: 630,
        widths: &[480, 945],
    },
    Image {
        key: "eloadok/medvegy-anna",
        width: 945,
        height: 629,
        widths: &[480, 945],
    },
    Image {
        key: "eloadok/nagy-balazs-vince",
        width: 944,
        height: 629,
        widths: &[480, 944],
    },
    Image {
        key: "eloadok/pacher-tibor",
        width: 944,
        height: 629,
        widths: &[480, 944],
    },
    Image {
        key: "eloadok/pal-andras",
        width: 944,
        height: 629,
        widths: &[480, 944],
    },
    Image {
        key: "eloadok/sarneczky-krisztian",
        width: 944,
        height: 629,
        widths: &[480, 944],
    },
    Image {
        key: "eloadok/somodi-mate",
        width: 945,
        height: 629,
        widths: &[480, 945],
    },
    Image {
        key: "eloadok/stepan-gabor",
        width: 945,
        height: 629,
        widths: &[480, 945],
    },
    Image {
        key: "eloadok/szabo-jozsef",
        width: 945,
        height: 630,
        widths: &[480, 945],
    },
    Image {
        key: "eloadok/szabo-nimrod",
        width: 945,
        height: 629,
        widths: &[480, 945],
    },
    Image {
        key: "eloadok/szabo-robert",
        width: 944,
        height: 629,
        widths: &[480, 944],
    },
    Image {
        key: "kozosseg/csapat-terasz",
        width: 1280,
        height: 720,
        widths: &[640, 1280],
    },
    Image {
        key: "kozosseg/csapat-terem",
        width: 1280,
        height: 852,
        widths: &[640, 1280],
    },
    Image {
        key: "kozosseg/csillagvizsgalo",
        width: 1280,
        height: 720,
        widths: &[640, 1280],
    },
    Image {
        key: "kozosseg/csoportkep",
        width: 1920,
        height: 1080,
        widths: &[640, 1280, 1920],
    },
    Image {
        key: "kozosseg/egbolt",
        width: 1920,
        height: 1080,
        widths: &[640, 1280, 1920],
    },
    Image {
        key: "kozosseg/eloadas-szinpad",
        width: 1280,
        height: 960,
        widths: &[640, 1280],
    },
    Image {
        key: "kozosseg/eloadas-terem",
        width: 1280,
        height: 964,
        widths: &[640, 1280],
    },
    Image {
        key: "kozosseg/eloadas-vetites",
        width: 1280,
        height: 720,
        widths: &[640, 1280],
    },
    Image {
        key: "kozosseg/irodaavato",
        width: 846,
        height: 506,
        widths: &[640, 846],
    },
    Image {
        key: "kozosseg/muhely",
        width: 1280,
        height: 852,
        widths: &[640, 1280],
    },
    Image {
        key: "sstv/20241012-125306",
        width: 640,
        height: 496,
        widths: &[320, 640],
    },
    Image {
        key: "sstv/20241113-002156",
        width: 640,
        height: 450,
        widths: &[320, 640],
    },
    Image {
        key: "sstv/20241113-202308",
        width: 640,
        height: 496,
        widths: &[320, 640],
    },
    Image {
        key: "sstv/20241114-193138",
        width: 640,
        height: 496,
        widths: &[320, 640],
    },
    Image {
        key: "sstv/20241114-224220",
        width: 640,
        height: 496,
        widths: &[320, 640],
    },
    Image {
        key: "sstv/20241115-235901",
        width: 640,
        height: 496,
        widths: &[320, 640],
    },
    Image {
        key: "sstv/20250103-230258",
        width: 640,
        height: 496,
        widths: &[320, 640],
    },
    Image {
        key: "sstv/20250103-230712",
        width: 640,
        height: 499,
        widths: &[320, 640],
    },
    Image {
        key: "sstv/20250412-092231",
        width: 640,
        height: 493,
        widths: &[320, 640],
    },
    Image {
        key: "sstv/20250415-114915",
        width: 640,
        height: 496,
        widths: &[320, 640],
    },
    Image {
        key: "sstv/img-3217",
        width: 640,
        height: 496,
        widths: &[320, 640],
    },
    Image {
        key: "sstv/pd120-20241116-173959",
        width: 640,
        height: 496,
        widths: &[320, 640],
    },
    Image {
        key: "sstv/pd120-20241116-174408",
        width: 640,
        height: 496,
        widths: &[320, 640],
    },
];

pub fn get(key: &str) -> Option<&'static Image> {
    IMAGES.iter().find(|i| i.key == key)
}
