//! Responsive images (AVIF with JPEG fallback) and inline icons.

use leptos::prelude::*;

use crate::{content::ImageRef, images};

/// `<picture>` for an image generated by tools/images.py. `sizes` describes the rendered width.
#[component]
pub fn Picture(
    #[prop(into)] key: String,
    #[prop(into)] alt: String,
    sizes: &'static str,
    /// Above the fold: load immediately with high priority.
    #[prop(optional)]
    eager: bool,
    #[prop(optional, into)] class: Option<String>,
) -> impl IntoView {
    let Some(image) = images::get(&key) else {
        leptos::logging::error!("unknown image key: {key}");
        return None;
    };
    let srcset = |ext: &str| {
        image
            .widths
            .iter()
            .map(|w| format!("/img/{}-{w}.{ext} {w}w", image.key))
            .collect::<Vec<_>>()
            .join(", ")
    };
    let largest = image.widths.last().copied().unwrap_or(image.width);
    Some(view! {
        <picture class=class>
            <source type="image/avif" srcset=srcset("avif") sizes=sizes/>
            <img
                src=format!("/img/{}-{largest}.jpg", image.key)
                srcset=srcset("jpg")
                sizes=sizes
                width=image.width.to_string()
                height=image.height.to_string()
                alt=alt
                loading=if eager { "eager" } else { "lazy" }
                fetchpriority=eager.then_some("high")
                decoding="async"
            />
        </picture>
    })
}

/// Rendered width of one `.gallery` grid tile (1180px container, minmax(260px, 1fr), 1rem gap).
pub const GRID_SIZES: &str = "(width > 1200px) 283px, (width > 900px) 30vw, (width > 600px) 46vw, 92vw";

/// Grid of images; each opens its largest JPEG. Photos of mixed shapes (portrait next to
/// landscape) get the masonry layout, so none is cropped.
#[component]
pub fn Gallery(
    images: Vec<ImageRef>,
    #[prop(optional, into)] class: Option<String>,
    /// `sizes` of every tile; must match the layout the class produces.
    #[prop(default = GRID_SIZES)]
    sizes: &'static str,
) -> impl IntoView {
    let ratios: Vec<f32> = images
        .iter()
        .filter_map(|i| images::get(&i.key))
        .map(|i| i.width as f32 / i.height as f32)
        .collect();
    let (lo, hi) = ratios.iter().fold((f32::MAX, 0f32), |(lo, hi), &r| (lo.min(r), hi.max(r)));
    let mixed = hi / lo > 1.2;
    let class = format!(
        "gallery {}{}",
        if mixed { "gallery-masonry " } else { "" },
        class.unwrap_or_default()
    );
    view! {
        <ul class=class role="list">
            {images
                .into_iter()
                .map(|image| {
                    let full = images::get(&image.key)
                        .map(|i| format!("/img/{}-{}.jpg", i.key, i.widths.last().copied().unwrap_or(i.width)))
                        .unwrap_or_default();
                    view! {
                        <li>
                            <a href=full>
                                <Picture key=image.key alt=image.alt sizes=sizes/>
                            </a>
                        </li>
                    }
                })
                .collect_view()}
        </ul>
    }
}

/// Inline SVG icon from `crate::icons` (decorative: the SVG carries aria-hidden).
#[component]
pub fn Icon(svg: &'static str) -> impl IntoView {
    view! { <span class="icon" inner_html=svg></span> }
}
