//! Responsive images (AVIF with JPEG fallback) and inline icons.

use leptos::prelude::*;

use crate::{content::ImageRef, images};

/// `<picture>` for an image generated by tools/images.py. `sizes` describes the rendered width.
#[component]
pub fn Picture(
    #[prop(into)] key: String,
    #[prop(into)] alt: String,
    sizes: &'static str,
    /// Above the fold: load immediately with high priority.
    #[prop(optional)]
    eager: bool,
    #[prop(optional, into)] class: Option<String>,
    /// Art direction: (media query, key of a differently cropped image, its `sizes`), used
    /// while the query matches, e.g. a portrait crop for a full-bleed hero on phones.
    #[prop(optional)]
    art: Option<(&'static str, &'static str, &'static str)>,
) -> impl IntoView {
    let Some(image) = images::get(&key) else {
        leptos::logging::error!("unknown image key: {key}");
        return None;
    };
    let largest = image.widths.last().copied().unwrap_or(image.width);
    let art = art.and_then(|(media, key, sizes)| {
        let alt_image = images::get(key);
        if alt_image.is_none() {
            leptos::logging::error!("unknown image key: {key}");
        }
        alt_image.map(|i| (media, i, sizes))
    });
    Some(view! {
        <picture class=class>
            {art.map(|(media, i, art_sizes)| view! {
                <source media=media type="image/avif" srcset=srcset(i, "avif") sizes=art_sizes/>
                <source media=media type="image/jpeg" srcset=srcset(i, "jpg") sizes=art_sizes/>
            })}
            <source type="image/avif" srcset=srcset(image, "avif") sizes=sizes/>
            <img
                src=format!("/img/{}-{largest}.jpg", image.key)
                srcset=srcset(image, "jpg")
                sizes=sizes
                width=image.width.to_string()
                height=image.height.to_string()
                alt=alt
                loading=if eager { "eager" } else { "lazy" }
                fetchpriority=eager.then_some("high")
                decoding="async"
            />
        </picture>
    })
}

fn srcset(image: &images::Image, ext: &str) -> String {
    image.widths.iter().map(|w| format!("/img/{}-{w}.{ext} {w}w", image.key)).collect::<Vec<_>>().join(", ")
}

/// Rendered width of one `.gallery` grid tile (1180px container, minmax(260px, 1fr), 1rem gap).
pub const GRID_SIZES: &str = "(width > 1200px) 283px, (width > 900px) 30vw, (width > 600px) 46vw, 92vw";

/// Grid of images; each opens its largest JPEG. Photos of mixed shapes (portrait next to
/// landscape) get the masonry layout, so none is cropped.
#[component]
pub fn Gallery(
    images: Vec<ImageRef>,
    #[prop(optional, into)] class: Option<String>,
    /// `sizes` of every tile; must match the layout the class produces.
    #[prop(default = GRID_SIZES)]
    sizes: &'static str,
    /// What to print under each image.
    #[prop(optional)]
    captions: Captions,
) -> impl IntoView {
    let ratios: Vec<f32> = images
        .iter()
        .filter_map(|i| images::get(&i.key))
        .map(|i| i.width as f32 / i.height as f32)
        .collect();
    let (lo, hi) = ratios.iter().fold((f32::MAX, 0f32), |(lo, hi), &r| (lo.min(r), hi.max(r)));
    let mixed = hi / lo > 1.2;
    let class = format!(
        "gallery {}{}",
        if mixed { "gallery-masonry " } else { "" },
        class.unwrap_or_default()
    );
    view! {
        <ul class=class role="list">
            {images
                .into_iter()
                .map(|image| {
                    let full = images::get(&image.key)
                        .map(|i| format!("/img/{}-{}.jpg", i.key, i.widths.last().copied().unwrap_or(i.width)))
                        .unwrap_or_default();
                    let caption_hidden = matches!(captions, Captions::Alt);
                    let (alt, caption) = match captions {
                        Captions::None => (image.alt, None),
                        // The alt names the link; the caption repeats it visually only.
                        Captions::Alt => (image.alt.clone(), Some(view! { {image.alt} }.into_any())),
                        Captions::ReceivedAt => {
                            let time = received_at(&image.key);
                            let caption = time.map(|(iso, label)| {
                                view! { <time datetime=iso>{label}</time> }.into_any()
                            });
                            (image.alt, caption)
                        }
                    };
                    view! {
                        <li>
                            <figure>
                                <a href=full>
                                    <Picture key=image.key alt=alt sizes=sizes/>
                                </a>
                                {caption.map(|c| view! {
                                    <figcaption aria-hidden=caption_hidden.then_some("true")>{c}</figcaption>
                                })}
                            </figure>
                        </li>
                    }
                })
                .collect_view()}
        </ul>
    }
}

/// Captions under gallery images.
#[derive(Clone, Copy, Default)]
pub enum Captions {
    #[default]
    None,
    /// The alt text (e.g. subject and photographer) shown as the caption too; the caption is
    /// hidden from screen readers because the alt already names the link.
    Alt,
    /// Reception time encoded in the file name of SSTV images ("sstv/20241113-202308").
    ReceivedAt,
}

/// ("2024-11-13T20:23:08", "2024.11.13. 20:23:08") from a key ending in YYYYMMDD-HHMMSS.
fn received_at(key: &str) -> Option<(String, String)> {
    let stem = key.rsplit('/').next()?;
    let digits: String = stem.chars().filter(char::is_ascii_digit).collect();
    let tail = digits.get(digits.len().checked_sub(14)?..)?;
    let (d, t) = tail.split_at(8);
    let (y, mo, da) = (&d[..4], &d[4..6], &d[6..]);
    let (h, mi, se) = (&t[..2], &t[2..4], &t[4..]);
    let valid = (1..=12).contains(&mo.parse::<u8>().ok()?) && (1..=31).contains(&da.parse::<u8>().ok()?);
    valid.then(|| (format!("{y}-{mo}-{da}T{h}:{mi}:{se}"), format!("{y}.{mo}.{da}. {h}:{mi}:{se}")))
}

#[cfg(test)]
mod tests {
    #[test]
    fn reception_times_from_file_names() {
        assert_eq!(
            super::received_at("sstv/20241113-202308").unwrap().1,
            "2024.11.13. 20:23:08"
        );
        assert_eq!(super::received_at("sstv/pd120-20241116-174408").unwrap().0, "2024-11-16T17:44:08");
        assert_eq!(super::received_at("sstv/img-3217"), None);
    }
}

/// Inline SVG icon from `crate::icons` (decorative: the SVG carries aria-hidden).
#[component]
pub fn Icon(svg: &'static str) -> impl IntoView {
    view! { <span class="icon" inner_html=svg></span> }
}
