//! Responsive images (AVIF with JPEG fallback) and inline icons.

use leptos::prelude::*;
use leptos_meta::Link;

use crate::{content::ImageRef, images};

/// A responsive image: `<base>-<w>.avif` and `<base>-<w>.jpg` for every width. Either generated
/// by tools/images.py (under /img/, see [`Img::by_key`]) or synced from Drive (under /drive/).
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Img {
    pub base: String,
    /// Size of the largest file.
    pub width: u32,
    pub height: u32,
    /// Ascending.
    pub widths: Vec<u32>,
}

impl Img {
    /// An image generated by tools/images.py.
    pub fn by_key(key: &str) -> Option<Self> {
        let image = images::get(key);
        if image.is_none() {
            leptos::logging::error!("unknown image key: {key}");
        }
        image.map(|i| Self {
            base: format!("/img/{}", i.key),
            width: i.width,
            height: i.height,
            widths: i.widths.to_vec(),
        })
    }

    fn srcset(&self, ext: &str) -> String {
        self.widths.iter().map(|w| format!("{}-{w}.{ext} {w}w", self.base)).collect::<Vec<_>>().join(", ")
    }

    /// The largest JPEG.
    pub fn src(&self) -> String {
        format!("{}-{}.jpg", self.base, self.widths.last().copied().unwrap_or(self.width))
    }

    /// The largest JPEG not wider than `max` (or the smallest one), with its size.
    pub fn jpeg_at_most(&self, max: u32) -> (String, u32, u32) {
        let w = self.widths.iter().rev().copied().find(|&w| w <= max).or(self.widths.first().copied()).unwrap_or(self.width);
        let h = (u64::from(self.height) * u64::from(w) / u64::from(self.width.max(1))) as u32;
        (format!("{}-{w}.jpg", self.base), w, h)
    }

    /// Width / height.
    pub fn ratio(&self) -> f32 {
        self.width as f32 / self.height.max(1) as f32
    }
}

/// `<picture>` for an image generated by tools/images.py. `sizes` describes the rendered width.
#[component]
pub fn Picture(
    #[prop(into)] key: String,
    #[prop(into)] alt: String,
    #[prop(into)] sizes: String,
    /// Above the fold: load immediately with high priority.
    #[prop(optional)]
    eager: bool,
    #[prop(optional, into)] class: Option<String>,
    /// Art direction: (media query, key of a differently cropped image, its `sizes`), used
    /// while the query matches, e.g. a portrait crop for a full-bleed hero on phones.
    #[prop(optional)]
    art: Option<(&'static str, &'static str, &'static str)>,
) -> impl IntoView {
    let image = Img::by_key(&key)?;
    let art = art.and_then(|(media, key, sizes)| Img::by_key(key).map(|i| (media, i, sizes)));
    Some(view! { <Responsive img=image alt sizes eager class art/> })
}

/// `<picture>` for any [`Img`].
#[component]
pub fn Responsive(
    img: Img,
    #[prop(into)] alt: String,
    #[prop(into)] sizes: String,
    /// Load right away (not lazily); implies high fetch priority unless `high` says otherwise.
    #[prop(optional)]
    eager: bool,
    #[prop(optional_no_strip)] high: Option<bool>,
    #[prop(optional_no_strip)] class: Option<String>,
    #[prop(optional_no_strip)] art: Option<(&'static str, Img, &'static str)>,
) -> impl IntoView {
    let priority = high.unwrap_or(eager);
    // A high-priority image is the page's largest one above the fold: it is announced in <head>,
    // so its download starts before the parser reaches the <img>. AVIF only, like the <source>
    // every current browser picks; with art direction one link per media query.
    let preload = priority.then(|| match &art {
        Some((media, i, art_sizes)) => view! {
            <Link rel="preload" as_="image" type_="image/avif" fetchpriority="high"
                media=*media imagesrcset=i.srcset("avif") imagesizes=*art_sizes/>
            <Link rel="preload" as_="image" type_="image/avif" fetchpriority="high"
                media=format!("not all and {media}") imagesrcset=img.srcset("avif") imagesizes=sizes.clone()/>
        }
        .into_any(),
        None => view! {
            <Link rel="preload" as_="image" type_="image/avif" fetchpriority="high"
                imagesrcset=img.srcset("avif") imagesizes=sizes.clone()/>
        }
        .into_any(),
    });
    view! {
        {preload}
        <picture class=class>
            {art.map(|(media, i, art_sizes)| view! {
                <source media=media type="image/avif" srcset=i.srcset("avif") sizes=art_sizes/>
                <source media=media type="image/jpeg" srcset=i.srcset("jpg") sizes=art_sizes/>
            })}
            <source type="image/avif" srcset=img.srcset("avif") sizes=sizes.clone()/>
            <img
                src=img.src()
                srcset=img.srcset("jpg")
                sizes=sizes
                width=img.width.to_string()
                height=img.height.to_string()
                alt=alt
                loading=if eager { "eager" } else { "lazy" }
                fetchpriority=priority.then_some("high")
                decoding="async"
            />
        </picture>
    }
}

/// Row height of the justified gallery wall at each breakpoint (style/main.css `.gallery`).
const ROW_DESKTOP_PX: f32 = 240.0;
const ROW_TABLET_VW: f32 = 18.0;
const ROW_MOBILE_PX: f32 = 120.0;

/// `sizes` of one tile of the justified wall: its share of a row is about its aspect ratio
/// times the row height, plus the stretch that fills the row (up to ~40%; small galleries,
/// whose rows stretch to the full width, up to 2x).
fn tile_sizes(ratio: f32, few: bool) -> String {
    let grow = if few { 2.0 } else { 1.4 } * ratio;
    // Phones wrap even small galleries into several rows: the plain stretch applies there.
    let grow_mobile = 1.4 * ratio;
    // On phones a small gallery's lone last tile spans the row.
    let mobile = if few { "92vw".to_owned() } else { format!("{:.0}px", (grow_mobile * ROW_MOBILE_PX).min(400.0)) };
    format!(
        "(width >= 1280px) {:.0}px, (width >= 768px) {:.1}vw, {mobile}",
        (grow * ROW_DESKTOP_PX).min(1200.0),
        (grow * ROW_TABLET_VW).min(92.0),
    )
}

/// One image of a [`Gallery`].
#[derive(Clone, Debug)]
pub struct Tile {
    pub img: Img,
    pub alt: String,
    /// Where the image links: its photo page, or the largest JPEG.
    pub href: String,
    /// `id` of the tile, so a link can return to it (`…#kep-<slug>`).
    pub id: Option<String>,
    pub caption: Option<Caption>,
}

impl Tile {
    /// A tile for a Markdown image that links to its largest JPEG.
    pub fn from_ref(image: &ImageRef) -> Option<Self> {
        let img = Img::by_key(&image.key)?;
        Some(Self { href: img.src(), img, alt: image.alt.clone(), id: None, caption: None })
    }
}

/// Text under a gallery image.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Caption {
    /// Repeats the alt text visually (e.g. subject and photographer); hidden from screen readers,
    /// because the alt already names the link.
    Text(String),
    /// Reception time of a radio image: (ISO datetime, label).
    Time(String, String),
}

/// A justified wall of linked images: every row has one height and each image keeps its own
/// shape (nothing is cropped). Each tile's width follows its aspect ratio (`--r`).
#[component]
pub fn Gallery(
    tiles: Vec<Tile>,
    #[prop(optional, into)] class: Option<String>,
    /// The first `eager` tiles load right away: use it when the gallery starts above the fold.
    #[prop(optional)]
    eager: usize,
) -> impl IntoView {
    let class = format!("gallery {}", class.unwrap_or_default());
    let few = tiles.len() < 7;
    view! {
        <ul class=class.trim_end().to_owned() role="list">
            {tiles
                .into_iter()
                .enumerate()
                .map(|(i, tile)| {
                    // Under a tile only real data (a reception time); descriptions are on the
                    // photo page and in the alt text.
                    let caption = match tile.caption {
                        Some(Caption::Time(iso, label)) => Some(view! {
                            <figcaption><time datetime=iso>{label}</time></figcaption>
                        }),
                        _ => None,
                    };
                    let ratio = tile.img.ratio();
                    view! {
                        <li id=tile.id style=format!("--r:{ratio:.3}")>
                            <figure>
                                <a href=tile.href>
                                    <Responsive
                                        img=tile.img
                                        alt=tile.alt
                                        sizes=tile_sizes(ratio, few)
                                        eager=i < eager
                                        high=Some(false)
                                    />
                                </a>
                                {caption}
                            </figure>
                        </li>
                    }
                })
                .collect_view()}
        </ul>
    }
}

/// Inline SVG icon from `crate::icons` (decorative: the SVG carries aria-hidden).
#[component]
pub fn Icon(svg: &'static str) -> impl IntoView {
    view! { <span class="icon" inner_html=svg></span> }
}
